# Generated by Django 4.2.6 on 2023-10-12 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='recipient',
            field=models.ManyToManyField(related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='получатели'),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newsletter.newsletter', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newsletter.mailingmessage', verbose_name='письмо'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newsletter.newsletter', verbose_name='рассылка'),
        ),
    ]
