# Generated by Django 4.2.6 on 2023-10-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='mailing_time',
            new_name='time',
        ),
    ]
