# Generated by Django 4.2.6 on 2023-10-24 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_rename_mailing_time_newsletter_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
        migrations.AddField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата и время последней попытки'),
            preserve_default=False,
        ),
    ]
